import type { Metadata } from "next";
import { Anonymous_Pro, Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const anon = Anonymous_Pro({subsets:["latin"], weight:["400","700"]})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={anon.className}>{children}</body>
    </html>
  );
}
